os:
  - ubuntu-latest
test_set:
  - accounting
  - auth
  - b2b
  - dialog
  - permissions
  - presence
  - record-route
  - registration
  - startup
  - stir-shaken
  - topology-hiding
  - uac-auth
params:
 - --exclude topology-hiding/02.th-no-dialog-username
