name: Build SIPSsert Image

env:
  COMPONENT: devel
  TAG: sipssert

on:
  workflow_dispatch:

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get the required OpenSIPS Modules
      id: fetch_modules
      run: echo "MODULES=$(cat .opensips.modules | tr '\n' ' ')" > $GITHUB_OUTPUT

    - name: Publish OpenSIPS SIPssert Docker image
      uses: OpenSIPS/docker-opensips/.github/actions/docker-opensips-publish@main
      with:
        component: $COMPONENT
        tag: $TAG
        cli: false
        modules: ${{ steps.fetch_modules.outputs.MODULES }}
        docker-username: ${{ secrets.DOCKER_USERNAME }}
        docker-token: ${{ secrets.DOCKER_TOKEN }}
