name: Build SIPSsert Image

on:
  workflow_dispatch:

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Get the required OpenSIPS Modules
      id: fetch_modules
      run: echo "MODULES=$(cat .opensips.modules | tr '\n' ' ')" > $GITHUB_OUTPUT

    - name: Publish OpenSIPS SIPssert Docker image
      uses: OpenSIPS/docker-opensips/.github/actions/docker-opensips-publish@main
      with:
        component: ${{ github.ref_name == github.event.repository.default_branch && 'devel' || format('{0}-nightly', github.ref_name) }}
        tag: ${{ github.ref_name == github.event.repository.default_branch && 'sipssert' || format('sipssert-{0}', github.ref_name) }}
        cli: false
        modules: ${{ steps.fetch_modules.outputs.MODULES }}
        docker-username: ${{ secrets.DOCKER_USERNAME }}
        docker-token: ${{ secrets.DOCKER_TOKEN }}
