name: Build SIPSsert Image

on:
  workflow_dispatch:
    inputs:
      component:
        description: OpenSIPS Version to publish
        type: choice
        options:
          - devel
          - 3.6-nightly
          - 3.4-nightly
        required: true
      tag:
        description: OpenSIPS SIPssert Tag to use
        required: true

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get the required OpenSIPS Modules
      id: fetch_modules
      run: echo "MODULES=$(cat .opensips.modules | tr '\n' ' ')" > $GITHUB_OUTPUT

    - name: Publish OpenSIPS SIPssert Docker image
      uses: OpenSIPS/docker-opensips/.github/actions/docker-opensips-publish@main
      with:
        component: ${{ github.event.inputs.component }}
        tag: ${{ github.event.inputs.tag }}
        cli: false
        modules: ${{ steps.fetch_modules.outputs.MODULES }}
        docker-username: ${{ secrets.DOCKER_USERNAME }}
        docker-token: ${{ secrets.DOCKER_TOKEN }}
